context:
  name: hatch-rs
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/hatch_rs/hatch_rs-${{ version }}.tar.gz
  sha256: cb5ef49c0a8a157704413ae024005041819302410369953ada062c293aaaa209

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - hatchling
    - pydantic

tests:
  - python:
      imports:
      - hatch_rs.hooks
      - hatch_rs.plugin
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: hatch plugin for rust
  homepage: https://github.com/python-project-templates/hatch-rs
  repository: https://github.com/python-project-templates/hatch-rs

extra:
  recipe-maintainers:
    - timkpaine
