context:
  name: hatch-rs
  version: "0.4.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/hatch_rs/hatch_rs-${{ version }}.tar.gz
  sha256: 1359769e3dfb9f005b72275d88bf7872384c42fc79fb68dd94988cf094b8a325

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - hatchling
    - pydantic

tests:
  - python:
      imports:
        - hatch_rs.hooks
        - hatch_rs.plugin
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: hatch plugin for rust
  homepage: https://github.com/python-project-templates/hatch-rs
  repository: https://github.com/python-project-templates/hatch-rs

extra:
  recipe-maintainers:
    - timkpaine
